#ifndef TOKENS_H_   /* Include guard */
#define TOKENS_H_

// tokens values
#define ABRECHAVES 1
#define ABRECOLCHETE 2
#define ABREPARENTESIS 3
#define ADDRESS 4
#define AFTER 5
#define ALL 6
#define ALLOF 7
#define ANYOF 8
#define ARROBA 9
#define ASCII_CASEMAP 10
#define ASPAS 11
#define BEFORE 12
#define BODY 13
#define BULK 14
#define CC 15
#define CERCA 16
#define COMPARATOR 17
#define CONTAINS 18
#define DATE 19
#define DISABLED_IF 20
#define DISCARD 21
#define DOISPONTOS 22
#define DOMAIN 23
#define ENDOFFILE 24
#define FECHACHAVES 25
#define FECHACOLCHETE 26
#define FECHAPARENTESIS 27
#define FILEINTO 28
#define FLAG 29
#define FROM 30
#define HEADER 31
#define ID 32
#define IDEXTENDED 33
#define IDFILTERNAME 34
#define IF 35
#define IN 36
#define IS 37
#define KEEP 38
#define LIST 39
#define MATCHES 40
#define ME 41
#define NAME 42
#define NOT 43
#define PONTO 44
#define PONTOEVIRGULA 45
#define READ 46
#define REDIRECT 47
#define REJECT 48
#define REQUIRE 49
#define SLASH 50
#define STOP 51
#define SUBJECT 52
#define TAG 53
#define TO 54
#define UNKOWN 55
#define VIRGULA 56
#define ZIMBRAMAILSIEVESCRIPT 57

#endif // TOKENS_H_

